global:
  host: "loadtesting.xix.in" #to be filled
  database:
    host: 
    user: "postgres"
    port: "5432"
    vendor: "postgres"
  keycloak:
    database: "keycloak"
    admin:
      username: "admin"
    proxy_forwarding: true
  registry:
    serviceaccount_name: "sbrc-sa"
    serviceaccount_role_arn: 
      eks.amazonaws.com/role-arn: "arn:aws:iam::370803901956:role/sbrc-eks-serviceaccount-role" 
    compute_type:
      eks.amazonaws.com/compute-type: "fargate"  
    database: "registry" # to be checked
    search_provider: "dev.sunbirdrc.registry.service.NativeSearchService"
    #search_provider: "dev.sunbirdrc.registry.service.ElasticSearchService" # to be checked
    sso:
      realm: "sunbird-rc"
      admin_client_id: "admin-api"
      client_id: "registry-frontend"
    signature_enabled: true
    keycloak_user_set_password: false
    base_apis_enabled: false
    log_level: INFO
    enable_external_templates: true
    enable_async: false
    enable_authentication: true
    enable_webhook: false
    webhook_url: http://localhost:5001/api/v1/callback
    manager_type: DefinitionsManager
  minio:
    url: https://s3.amazonaws.com
    #access_key: 
    bucket_key: sbrc-registry
  elastic_search:
    url:
    auth_enabled: false
    username: "opensearch"
  kafka:
    url:
  redis:
    host:
    port: 6379
  secrets:
    DB_PASSWORD: 
    ELASTIC_SEARCH_PASSWORD: 
    KEYCLOAK_ADMIN_CLIENT_SECRET: 
    KEYCLOAK_ADMIN_PASSWORD: 
    KEYCLOAK_DEFAULT_USER_PASSWORD: 
    MINIO_SECRET_KEY:
    access_key:
